# MIT License
#
# Copyright (c) 2017 HyperdriveMe, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from json import loads

import os
import socket
import time
import urllib2, base64

APIKey = '< hosted graphite api key>'
# get this from https://www.hostedgraphite.com/app/accesskey/#
# copy the link for HG autogenerated (graphite)
# should look something like /XXXXXXXX/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/graphite/
AccessKey = '< hosted graphite access key>'

def load_file(filename):
	try:
		if os.path.exists(filename): return file(filename).readlines();

	except Exception, inst:
		print 'file_get.error:', filename, inst


def send_stat(key, value):
	conn = socket.create_connection(("carbon.hostedgraphite.com", 2003))
	metric = "%s.hyperdrive.%s %s\n" % (APIKey, key, value)
	print metric
	conn.send(metric)
	conn.close()


# get this from https://www.hostedgraphite.com/app/accesskey/#
# copy the link for HG autogenerated (graphite)
# more info on building queries for graphite -> http://graphite.readthedocs.io/en/latest/render_api.html
def get_stat(key):
	url = 'https://www.hostedgraphite.com'+AccessKey+'render?target=summarize(hyperdrive.*,"10s")&format=json&from=-10s&until=now'
	return urllib2.urlopen(url).read()


# logData = loads('['+('\r,'.join(load_file('../../_data/obd.log')))+']')
# print logData

# for frame in logData:
# 	print '>>', frame
# 	for key in ['RPM','SPEED','MAF']:
# 		send_stat(key, frame[key])

print get_stat('RPM')
